[package]
name = "dec08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input_curler = { version = "0.1.0", path = "../input_curler" }
num = "0.4.1"
regex = "1.10.2"
